name: Lets Explore
favicon: null
layout_spectrum: 0.2596731726080179
typography_spectrum: 0.7966288682073355
title: Lets Explore
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6292622231412679
  lightness: 0.6389671913348138
  saturation: 0.9242815400939435
  rhythmicContrast: 0.3753732806071639
purpose: []
